micronaut:
  application:
    name: acmeFilms
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://acmedb.cbgvxyfea0se.us-east-1.rds.amazonaws.com:3306/acme_films?verifyServerCertificate=false&useSSL=false`}
    username: ${JDBC_USER:acmeuser}
    password: ${JDBC_PASSWORD:123456}
    dialect: MYSQL
    driverClassName: ${JDBC_DRIVER:com.mysql.cj.jdbc.Driver}
